//! Embedded, compile-time recovery-account public-key **PIN** (Wave-1 groundwork).
//!
//! The trusted recovery account is a wrap target for every upload's recovery
//! grant. Its PUBLIC encryption key is baked into this binary at build time (the
//! "embedded pin") — mirroring the `include_bytes!` embed pattern of
//! [`crate::ffmpeg_bin`] — and any server-served recovery key is only ever
//! COMPARED against it, never trusted on its own. Uploads wrap to the pin; a
//! mismatch trips a trust alarm ([`TrustAlarm::RecoveryPinMismatch`], alarm-A in
//! T8) rather than silently wrapping to a server-substituted key.
//!
//! # Canonical pin byte format (defined ONCE here; reused by T5/T8/T14)
//! The pin is the canonical serialization of the recovery **encryption** pubkey,
//! which is PQ-hybrid: an X25519 key plus an OPTIONAL ML-KEM-768 key. The layout
//! matches `maxsecu-encoding`'s canonical `Option<MlKemPub>` (a 1-byte presence
//! tag, no length prefix — the sizes are structural):
//! ```text
//! enc_pub            : 32   bytes  (X25519)
//! mlkem_present_tag  : 1    byte   (0x00 = absent, 0x01 = present)
//! mlkem_pub          : 1184 bytes  (ONLY present when tag == 0x01)
//! ```
//! So a classical-only pin is 33 bytes; a hybrid pin is 1217 bytes. Covering the
//! ML-KEM half matters: if the pin omitted it, a malicious server could swap just
//! the ML-KEM key undetected. [`compare_served`] compares the WHOLE blob
//! byte-for-byte in constant time, so a swap in EITHER half trips the alarm.
//!
//! # Build-time embed (`build.rs`)
//! `build.rs` reads a gitignored `recovery_pin.bin` from the crate root and emits
//! `EMBEDDED_PIN` into `OUT_DIR/recovery_pin_gen.rs`:
//! * file present  → the pin is those bytes;
//! * file absent + `unpinned-dev` feature → a clearly-labelled NON-SECURE test
//!   pin (a 33-byte classical pin of `0xA5`), for tests only;
//! * file absent + no feature → the build FAILS CLOSED (no silent zero pin that
//!   would disable the protection).
//!
//! Because the pin is embedded at BUILD time, the client must be rebuilt after
//! `maxsecu-setup` (T14) writes `recovery_pin.bin` — that is by design.

// Wave-1 groundwork: the public API here (`embedded_pin`, `compare_served`,
// `canonical_pin`, `TrustAlarm`, and the generated `EMBEDDED_PIN`) is first
// consumed by T8 (upload auto-wrap alarm-A). Until then it is dead code by
// design — the allow keeps this scaffolding build clean.
#![allow(dead_code)]

// `EMBEDDED_PIN: &[u8]` — generated by `build.rs` (see the module docs above).
include!(concat!(env!("OUT_DIR"), "/recovery_pin_gen.rs"));

/// X25519 public-key length (the classical half of the recovery enc key).
const X25519_PUB_LEN: usize = 32;

/// ML-KEM-768 encapsulation (public) key length — matches
/// `maxsecu_encoding::structs::MLKEM768_PUB_LEN`.
const MLKEM768_PUB_LEN: usize = 1184;

/// A detected breach of a compile-time trust anchor. Rendered as a
/// `server_untrusted`-class message by the UI (later tasks).
///
/// Intentionally a plain, extensible enum: T9 adds a TOFU-user-key-changed
/// variant (alarm-B) and T10 adds a transparency-failure variant (alarm-C).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TrustAlarm {
    /// The server-served recovery encryption pubkey does not byte-for-byte match
    /// the pin compiled into this client (alarm-A). Either half (X25519 or
    /// ML-KEM) differing trips this.
    RecoveryPinMismatch,
    /// A previously TOFU-pinned OTHER user's directory key now resolves to a
    /// DIFFERENT key (alarm-B, [`crate::tofu`]). Carries the affected `username`
    /// so the UI can render a `server_untrusted`-class message naming it. Raised
    /// on a change only — a first sighting is normal TOFU and never trips this.
    UserKeyChanged { username: String },
}

/// The recovery-account encryption pubkey pin compiled into this binary.
pub fn embedded_pin() -> &'static [u8] {
    EMBEDDED_PIN
}

/// Build the canonical pin bytes from the recovery enc pubkey halves. This is the
/// ONE encoder shared by producers (T14 `maxsecu-setup`, T5's server endpoint)
/// and consumers, so the byte layout can never drift between them.
///
/// Panics if `mlkem_pub` is `Some` but not exactly [`MLKEM768_PUB_LEN`] bytes —
/// a programmer error (a malformed key must never be silently pinned).
pub fn canonical_pin(enc_pub: &[u8; 32], mlkem_pub: Option<&[u8]>) -> Vec<u8> {
    let mut out = Vec::with_capacity(match mlkem_pub {
        None => X25519_PUB_LEN + 1,
        Some(_) => X25519_PUB_LEN + 1 + MLKEM768_PUB_LEN,
    });
    out.extend_from_slice(enc_pub);
    match mlkem_pub {
        None => out.push(0x00),
        Some(m) => {
            assert_eq!(
                m.len(),
                MLKEM768_PUB_LEN,
                "mlkem_pub must be exactly {MLKEM768_PUB_LEN} bytes"
            );
            out.push(0x01);
            out.extend_from_slice(m);
        }
    }
    out
}

/// Constant-time compare of a server-served recovery pin against the embedded
/// pin. Returns `Ok(())` on an exact byte-for-byte match, else
/// `Err(TrustAlarm::RecoveryPinMismatch)`.
///
/// A length mismatch is a mismatch. The comparison never short-circuits on the
/// first differing byte, so it leaks no information about WHERE (or whether) a
/// substitution occurred.
pub fn compare_served(served: &[u8]) -> Result<(), TrustAlarm> {
    if ct_eq(served, EMBEDDED_PIN) {
        Ok(())
    } else {
        Err(TrustAlarm::RecoveryPinMismatch)
    }
}

/// Constant-time byte-slice equality. Differing lengths compare unequal; equal
/// lengths are compared in full with an OR-accumulator (no early return), so the
/// timing is independent of the position of the first difference.
fn ct_eq(a: &[u8], b: &[u8]) -> bool {
    // A length difference is folded in as an unconditional mismatch. The
    // security-relevant path (served vs pin of the same length) then runs the
    // full-width accumulator below.
    let mut diff: u8 = (a.len() != b.len()) as u8;
    let n = a.len().min(b.len());
    for i in 0..n {
        diff |= a[i] ^ b[i];
    }
    diff == 0
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn embedded_pin_is_test_pin() {
        // Under `unpinned-dev` with no `recovery_pin.bin`, the compiled pin is the
        // labelled 33-byte classical test pin (0xA5 × 32, absent-ML-KEM tag).
        let expected = canonical_pin(&[0xA5u8; 32], None);
        assert_eq!(embedded_pin(), expected.as_slice());
    }

    #[test]
    fn compare_served_matches_identical() {
        assert!(compare_served(embedded_pin()).is_ok());
    }

    #[test]
    fn compare_served_rejects_different_blob() {
        let bogus = vec![0x00u8; 33];
        assert_eq!(compare_served(&bogus), Err(TrustAlarm::RecoveryPinMismatch));
    }

    #[test]
    fn compare_served_rejects_wrong_length() {
        assert_eq!(compare_served(&[]), Err(TrustAlarm::RecoveryPinMismatch));
        assert_eq!(
            compare_served(&vec![0xA5u8; 64]),
            Err(TrustAlarm::RecoveryPinMismatch)
        );
    }

    // The ML-KEM half is covered by the compare: two hybrid pins identical in the
    // X25519 half but differing ONLY in the ML-KEM half must compare unequal.
    #[test]
    fn ct_compare_covers_mlkem_half() {
        let enc = [0x11u8; 32];
        let mlkem_a = vec![0x22u8; 1184];
        let mut mlkem_b = mlkem_a.clone();
        mlkem_b[1183] ^= 0xFF; // differ only in the last ML-KEM byte
        let pin_a = canonical_pin(&enc, Some(&mlkem_a));
        let pin_b = canonical_pin(&enc, Some(&mlkem_b));
        assert_eq!(pin_a.len(), 1217);
        assert_eq!(pin_b.len(), 1217);
        assert_eq!(&pin_a[..33], &pin_b[..33]); // X25519 halves equal
        assert_ne!(pin_a, pin_b); // ML-KEM halves differ
        assert!(!ct_eq(&pin_a, &pin_b));
        assert!(ct_eq(&pin_a, &pin_a));
    }

    #[test]
    fn canonical_pin_lengths_and_tags() {
        let classical = canonical_pin(&[0u8; 32], None);
        assert_eq!(classical.len(), 33);
        assert_eq!(classical[32], 0x00);

        let mlkem = vec![0u8; 1184];
        let hybrid = canonical_pin(&[0u8; 32], Some(&mlkem));
        assert_eq!(hybrid.len(), 1217);
        assert_eq!(hybrid[32], 0x01);
    }

    #[test]
    #[should_panic]
    fn canonical_pin_rejects_bad_mlkem_length() {
        let _ = canonical_pin(&[0u8; 32], Some(&vec![0u8; 100]));
    }
}
