//! Embedded, compile-time recovery-account public-key **PIN** (Wave-1 groundwork).
//!
//! The trusted recovery account is a wrap target for every upload's recovery
//! grant. Its PUBLIC encryption key is baked into this binary at build time (the
//! "embedded pin") — mirroring the `include_bytes!` embed pattern of
//! [`crate::ffmpeg_bin`] — and any server-served recovery key is only ever
//! COMPARED against it, never trusted on its own. Uploads wrap to the pin; a
//! mismatch trips a trust alarm ([`TrustAlarm::RecoveryPinMismatch`], alarm-A in
//! T8) rather than silently wrapping to a server-substituted key.
//!
//! # Canonical pin byte format (defined ONCE here; reused by T5/T8/T14)
//! The pin is the canonical serialization of the recovery **encryption** pubkey,
//! which is PQ-hybrid: an X25519 key plus an OPTIONAL ML-KEM-768 key. The layout
//! matches `maxsecu-encoding`'s canonical `Option<MlKemPub>` (a 1-byte presence
//! tag, no length prefix — the sizes are structural):
//! ```text
//! enc_pub            : 32   bytes  (X25519)
//! mlkem_present_tag  : 1    byte   (0x00 = absent, 0x01 = present)
//! mlkem_pub          : 1184 bytes  (ONLY present when tag == 0x01)
//! ```
//! So a classical-only pin is 33 bytes; a hybrid pin is 1217 bytes. Covering the
//! ML-KEM half matters: if the pin omitted it, a malicious server could swap just
//! the ML-KEM key undetected. [`compare_served`] compares the WHOLE blob
//! byte-for-byte in constant time, so a swap in EITHER half trips the alarm.
//!
//! # Build-time embed (`build.rs`)
//! `build.rs` reads a gitignored `recovery_pin.bin` from the crate root and emits
//! `EMBEDDED_PIN` into `OUT_DIR/recovery_pin_gen.rs`:
//! * file present  → the pin is those bytes (via `include_bytes!`);
//! * file absent + `unpinned-dev` feature → a clearly-labelled NON-SECURE test
//!   pin: a REAL, fixed-seed HYBRID keypair (X25519 + ML-KEM-768), for tests only.
//!   Its matching PRIVATE key is reconstructable from the same fixed seeds via
//!   [`test_recovery_secret_seeds`], so a test can actually UNWRAP a recovery wrap;
//! * file absent + no feature → the build FAILS CLOSED (no silent zero pin that
//!   would disable the protection).
//!
//! Because the pin is embedded at BUILD time, the client must be rebuilt after
//! `maxsecu-setup` (T14) writes `recovery_pin.bin` — that is by design.

// `EMBEDDED_PIN: &[u8]` — generated by `build.rs` (see the module docs above).
include!(concat!(env!("OUT_DIR"), "/recovery_pin_gen.rs"));

/// X25519 public-key length (the classical half of the recovery enc key).
const X25519_PUB_LEN: usize = 32;

/// ML-KEM-768 encapsulation (public) key length — matches
/// `maxsecu_encoding::structs::MLKEM768_PUB_LEN`.
const MLKEM768_PUB_LEN: usize = 1184;

/// A detected breach of a compile-time trust anchor. Rendered as a
/// `server_untrusted`-class message by the UI (later tasks).
///
/// Intentionally a plain, extensible enum: T9 adds a TOFU-user-key-changed
/// variant (alarm-B) and T10 adds a transparency-failure variant (alarm-C).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TrustAlarm {
    /// The server-served recovery encryption pubkey does not byte-for-byte match
    /// the pin compiled into this client (alarm-A). Either half (X25519 or
    /// ML-KEM) differing trips this.
    RecoveryPinMismatch,
    /// A previously TOFU-pinned OTHER user's directory key now resolves to a
    /// DIFFERENT key (alarm-B, [`crate::tofu`]). Carries the affected `username`
    /// so the UI can render a `server_untrusted`-class message naming it. Raised
    /// on a change only — a first sighting is normal TOFU and never trips this.
    UserKeyChanged { username: String },
    /// A served directory binding could not be proven present in the directory
    /// key-transparency log under a pinned, non-equivocating checkpoint (alarm-C,
    /// [`crate::transparency`]). Raised when the KT checkpoint is not signed by a
    /// pinned KT log key, equivocates/rolls back against the persisted gossip
    /// checkpoint, or the binding is not provably included — i.e. the server
    /// equivocated about keys. Surfaced as `server_untrusted` and BLOCKS the
    /// browse/open (no content shown).
    TransparencyFailure,
}

/// The recovery-account encryption pubkey pin compiled into this binary.
pub fn embedded_pin() -> &'static [u8] {
    EMBEDDED_PIN
}

/// Build the canonical pin bytes from the recovery enc pubkey halves. This is the
/// ONE encoder shared by producers (T14 `maxsecu-setup`, T5's server endpoint)
/// and consumers, so the byte layout can never drift between them.
///
/// Panics if `mlkem_pub` is `Some` but not exactly [`MLKEM768_PUB_LEN`] bytes —
/// a programmer error (a malformed key must never be silently pinned).
pub fn canonical_pin(enc_pub: &[u8; 32], mlkem_pub: Option<&[u8]>) -> Vec<u8> {
    let mut out = Vec::with_capacity(match mlkem_pub {
        None => X25519_PUB_LEN + 1,
        Some(_) => X25519_PUB_LEN + 1 + MLKEM768_PUB_LEN,
    });
    out.extend_from_slice(enc_pub);
    match mlkem_pub {
        None => out.push(0x00),
        Some(m) => {
            assert_eq!(
                m.len(),
                MLKEM768_PUB_LEN,
                "mlkem_pub must be exactly {MLKEM768_PUB_LEN} bytes"
            );
            out.push(0x01);
            out.extend_from_slice(m);
        }
    }
    out
}

/// The decoded halves of a canonical pin: the X25519 `enc_pub` and the OPTIONAL
/// ML-KEM-768 encapsulation key. Owned so callers can hand the bytes straight to
/// the wrap primitives (`EncPublicKey::from_bytes` / `UploadParams`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParsedPin {
    pub enc_pub: [u8; 32],
    pub mlkem_pub: Option<[u8; MLKEM768_PUB_LEN]>,
}

/// Decode canonical pin bytes back into their halves — the inverse of
/// [`canonical_pin`]. Fail-closed (`None`) on any malformed length/tag: a 33-byte
/// classical pin (`tag 0x00`) or a `33 + 1184`-byte hybrid pin (`tag 0x01`) are the
/// ONLY accepted shapes. Used by the upload to wrap to the EMBEDDED pin's keys.
pub fn parse_pin(bytes: &[u8]) -> Option<ParsedPin> {
    if bytes.len() < X25519_PUB_LEN + 1 {
        return None;
    }
    let mut enc_pub = [0u8; 32];
    enc_pub.copy_from_slice(&bytes[..X25519_PUB_LEN]);
    match bytes[X25519_PUB_LEN] {
        0x00 if bytes.len() == X25519_PUB_LEN + 1 => Some(ParsedPin {
            enc_pub,
            mlkem_pub: None,
        }),
        0x01 if bytes.len() == X25519_PUB_LEN + 1 + MLKEM768_PUB_LEN => {
            let mut mlkem = [0u8; MLKEM768_PUB_LEN];
            mlkem.copy_from_slice(&bytes[X25519_PUB_LEN + 1..]);
            Some(ParsedPin {
                enc_pub,
                mlkem_pub: Some(mlkem),
            })
        }
        _ => None,
    }
}

/// The FIXED, well-known seeds the `unpinned-dev` test pin is derived from: a
/// 32-byte X25519 secret scalar and a 64-byte ML-KEM-768 decapsulation-key seed.
/// Reconstruct the recovery PRIVATE key in a test with
/// `HybridEncSecretKey::from_components(x25519_seed, mlkem_seed)`.
///
/// **NON-SECURE / TEST-ONLY.** These are compile-time constants embedded only
/// under `unpinned-dev`; the real recovery private key NEVER lives on any client —
/// only the public pin is embedded (the setup tool T14 holds the real secret).
/// MUST stay in sync with the seeds in `build.rs`.
#[cfg(feature = "unpinned-dev")]
pub fn test_recovery_secret_seeds() -> ([u8; 32], [u8; 64]) {
    ([0x5A; 32], [0x5B; 64])
}

/// Constant-time compare of a server-served recovery pin against the embedded
/// pin. Returns `Ok(())` on an exact byte-for-byte match, else
/// `Err(TrustAlarm::RecoveryPinMismatch)`.
///
/// A length mismatch is a mismatch. The comparison never short-circuits on the
/// first differing byte, so it leaks no information about WHERE (or whether) a
/// substitution occurred.
pub fn compare_served(served: &[u8]) -> Result<(), TrustAlarm> {
    if ct_eq(served, EMBEDDED_PIN) {
        Ok(())
    } else {
        Err(TrustAlarm::RecoveryPinMismatch)
    }
}

/// Constant-time byte-slice equality. Differing lengths compare unequal; equal
/// lengths are compared in full with an OR-accumulator (no early return), so the
/// timing is independent of the position of the first difference.
///
/// The two operands here are both PUBLIC keys (a server-served recovery pubkey vs
/// the compiled-in pin), so this reduced hand-rolled comparator is acceptable in
/// place of `subtle`: there is no secret whose bytes a timing side-channel could
/// leak — constant-time is kept only to avoid leaking WHERE a substitution differs.
fn ct_eq(a: &[u8], b: &[u8]) -> bool {
    // A length difference is folded in as an unconditional mismatch. The
    // security-relevant path (served vs pin of the same length) then runs the
    // full-width accumulator below.
    let mut diff: u8 = (a.len() != b.len()) as u8;
    let n = a.len().min(b.len());
    for i in 0..n {
        diff |= a[i] ^ b[i];
    }
    diff == 0
}

#[cfg(test)]
mod tests {
    use super::*;

    #[cfg(feature = "unpinned-dev")]
    #[test]
    fn embedded_pin_is_test_pin() {
        // Under `unpinned-dev` with no `recovery_pin.bin`, the compiled pin is the
        // labelled HYBRID test pin: canonical_pin(x25519_pub, Some(mlkem_pub)) for
        // the FIXED test seeds. Re-derive it here and assert equality — this ties
        // the build.rs output to `test_recovery_secret_seeds()` (any seed drift
        // between the two fails this test).
        let (x_seed, mlkem_seed) = test_recovery_secret_seeds();
        let enc_pub = maxsecu_crypto::x25519_public_from_secret(&x_seed);
        let mlkem_pub = maxsecu_crypto::mlkem_public_from_seed(&mlkem_seed).unwrap();
        let expected = canonical_pin(&enc_pub, Some(&mlkem_pub));
        assert_eq!(embedded_pin(), expected.as_slice());
        assert_eq!(embedded_pin().len(), 1217, "hybrid pin is 1217 bytes");
    }

    /// `parse_pin` is the exact inverse of `canonical_pin` for both shapes.
    #[test]
    fn parse_pin_round_trips_canonical_pin() {
        // Classical.
        let enc = [0x11u8; 32];
        let p = parse_pin(&canonical_pin(&enc, None)).unwrap();
        assert_eq!(p.enc_pub, enc);
        assert_eq!(p.mlkem_pub, None);
        // Hybrid.
        let mlkem = [0x22u8; 1184];
        let p = parse_pin(&canonical_pin(&enc, Some(&mlkem))).unwrap();
        assert_eq!(p.enc_pub, enc);
        assert_eq!(p.mlkem_pub, Some(mlkem));
    }

    #[test]
    fn parse_pin_rejects_malformed() {
        assert!(parse_pin(&[]).is_none()); // too short
        assert!(parse_pin(&[0u8; 32]).is_none()); // no tag
        assert!(parse_pin(&[0u8; 34]).is_none()); // classical tag but wrong length
        // Present tag but truncated ML-KEM.
        let mut bad = vec![0u8; 32];
        bad.push(0x01);
        bad.extend_from_slice(&[0u8; 1000]);
        assert!(parse_pin(&bad).is_none());
        // Unknown tag.
        let mut bad_tag = vec![0u8; 32];
        bad_tag.push(0x02);
        assert!(parse_pin(&bad_tag).is_none());
    }

    #[test]
    fn compare_served_matches_identical() {
        assert!(compare_served(embedded_pin()).is_ok());
    }

    #[test]
    fn compare_served_rejects_different_blob() {
        let bogus = vec![0x00u8; 33];
        assert_eq!(compare_served(&bogus), Err(TrustAlarm::RecoveryPinMismatch));
    }

    #[test]
    fn compare_served_rejects_wrong_length() {
        assert_eq!(compare_served(&[]), Err(TrustAlarm::RecoveryPinMismatch));
        assert_eq!(
            compare_served(&vec![0xA5u8; 64]),
            Err(TrustAlarm::RecoveryPinMismatch)
        );
    }

    // The ML-KEM half is covered by the compare: two hybrid pins identical in the
    // X25519 half but differing ONLY in the ML-KEM half must compare unequal.
    #[test]
    fn ct_compare_covers_mlkem_half() {
        let enc = [0x11u8; 32];
        let mlkem_a = vec![0x22u8; 1184];
        let mut mlkem_b = mlkem_a.clone();
        mlkem_b[1183] ^= 0xFF; // differ only in the last ML-KEM byte
        let pin_a = canonical_pin(&enc, Some(&mlkem_a));
        let pin_b = canonical_pin(&enc, Some(&mlkem_b));
        assert_eq!(pin_a.len(), 1217);
        assert_eq!(pin_b.len(), 1217);
        assert_eq!(&pin_a[..33], &pin_b[..33]); // X25519 halves equal
        assert_ne!(pin_a, pin_b); // ML-KEM halves differ
        assert!(!ct_eq(&pin_a, &pin_b));
        assert!(ct_eq(&pin_a, &pin_a));
    }

    #[test]
    fn canonical_pin_lengths_and_tags() {
        let classical = canonical_pin(&[0u8; 32], None);
        assert_eq!(classical.len(), 33);
        assert_eq!(classical[32], 0x00);

        let mlkem = vec![0u8; 1184];
        let hybrid = canonical_pin(&[0u8; 32], Some(&mlkem));
        assert_eq!(hybrid.len(), 1217);
        assert_eq!(hybrid[32], 0x01);
    }

    #[test]
    #[should_panic]
    fn canonical_pin_rejects_bad_mlkem_length() {
        let _ = canonical_pin(&[0u8; 32], Some(&vec![0u8; 100]));
    }
}
