use std::env;
use std::path::Path;

fn main() {
    tauri_build::build();
    generate_recovery_pin();
}

/// Emit `OUT_DIR/recovery_pin_gen.rs` defining `EMBEDDED_PIN: &[u8]`, the
/// compile-time recovery-account pubkey pin consumed by `src/recovery_pin.rs`.
///
/// Precedence:
/// * `recovery_pin.bin` present in the crate root → embed its bytes verbatim via
///   `include_bytes!` (the real, production path; `maxsecu-setup` (T14) writes it);
/// * file absent + `unpinned-dev` feature on → a clearly-labelled NON-SECURE
///   TEST pin: a REAL, fixed-seed HYBRID keypair (X25519 + ML-KEM-768) so tests
///   can reconstruct its private half and actually unwrap the recovery wrap;
/// * file absent + feature off → **FAIL THE BUILD CLOSED** (no silent zero/empty
///   pin that would disable the recovery-pin protection).
///
/// The two fixed test seeds below MUST stay byte-for-byte in sync with
/// `recovery_pin::test_recovery_secret_seeds()`; the `embedded_pin_is_test_pin`
/// unit test re-derives the pin from those seeds and asserts equality, so any
/// drift fails that test.
fn generate_recovery_pin() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let pin_path = Path::new(&manifest_dir).join("recovery_pin.bin");
    let gen_path = Path::new(&out_dir).join("recovery_pin_gen.rs");

    // Rebuild when the pin file appears/changes, or when the feature flips.
    println!("cargo:rerun-if-changed=recovery_pin.bin");
    println!("cargo:rerun-if-env-changed=CARGO_FEATURE_UNPINNED_DEV");

    let unpinned_dev = env::var_os("CARGO_FEATURE_UNPINNED_DEV").is_some();

    let generated = if pin_path.exists() {
        // Embed the real pin via `include_bytes!` of an absolute path (the gen file
        // lives in OUT_DIR, so a relative path would not resolve). `{:?}` on a Path
        // emits a correctly-escaped Rust string literal. The array→slice unsizing
        // coercion in const context gives the declared `&[u8]` type.
        format!(
            "// @generated by build.rs from recovery_pin.bin — DO NOT EDIT.\n\
             pub(crate) const EMBEDDED_PIN: &[u8] = include_bytes!({pin_path:?});\n"
        )
    } else if unpinned_dev {
        // NON-SECURE, TEST-ONLY pin. A REAL hybrid keypair derived from FIXED,
        // well-known seeds — NOT a placeholder — so the test suite can reconstruct
        // the matching PRIVATE key and genuinely unwrap the recovery wrap. This
        // MUST NEVER SHIP; a real build embeds a genuine pin or (below) fails closed.
        println!(
            "cargo:warning=recovery_pin: NON-SECURE test pin embedded (unpinned-dev) — do not ship"
        );
        // Fixed seeds — keep in sync with recovery_pin::test_recovery_secret_seeds().
        const TEST_X25519_SEED: [u8; 32] = [0x5A; 32];
        const TEST_MLKEM_SEED: [u8; 64] = [0x5B; 64];
        let enc_pub = maxsecu_crypto::x25519_public_from_secret(&TEST_X25519_SEED);
        let mlkem_pub = maxsecu_crypto::mlkem_public_from_seed(&TEST_MLKEM_SEED)
            .expect("fixed 64-byte ML-KEM test seed derives a public key");
        // Canonical pin layout: enc_pub(32) ‖ 0x01 (ML-KEM present) ‖ mlkem_pub(1184).
        // (Kept inline — build.rs cannot import src/recovery_pin.rs's canonical_pin.)
        let mut test_pin = Vec::with_capacity(32 + 1 + 1184);
        test_pin.extend_from_slice(&enc_pub);
        test_pin.push(0x01);
        test_pin.extend_from_slice(&mlkem_pub);
        format!(
            "// @generated by build.rs — NON-SECURE HYBRID TEST PIN (unpinned-dev). NEVER SHIP.\n\
             pub(crate) const EMBEDDED_PIN: &[u8] = &{test_pin:?};\n"
        )
    } else {
        panic!(
            "recovery_pin.bin missing — run maxsecu-setup and rebuild, or use \
             --features unpinned-dev for tests"
        );
    };

    std::fs::write(&gen_path, generated).expect("write recovery_pin_gen.rs");
}
