use std::env;
use std::path::Path;

fn main() {
    tauri_build::build();
    generate_recovery_pin();
}

/// Emit `OUT_DIR/recovery_pin_gen.rs` defining `EMBEDDED_PIN: &[u8]`, the
/// compile-time recovery-account pubkey pin consumed by `src/recovery_pin.rs`.
///
/// Precedence:
/// * `recovery_pin.bin` present in the crate root → embed its bytes verbatim
///   (the real, production path; `maxsecu-setup` (T14) writes this file);
/// * file absent + `unpinned-dev` feature on → a clearly-labelled NON-SECURE
///   TEST pin (33-byte classical `0xA5` pattern), for tests only;
/// * file absent + feature off → **FAIL THE BUILD CLOSED** (no silent zero/empty
///   pin that would disable the recovery-pin protection).
fn generate_recovery_pin() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let pin_path = Path::new(&manifest_dir).join("recovery_pin.bin");
    let gen_path = Path::new(&out_dir).join("recovery_pin_gen.rs");

    // Rebuild when the pin file appears/changes, or when the feature flips.
    println!("cargo:rerun-if-changed=recovery_pin.bin");
    println!("cargo:rerun-if-env-changed=CARGO_FEATURE_UNPINNED_DEV");

    let unpinned_dev = env::var_os("CARGO_FEATURE_UNPINNED_DEV").is_some();

    let generated = if pin_path.exists() {
        let bytes = std::fs::read(&pin_path).expect("read recovery_pin.bin");
        format!(
            "// @generated by build.rs from recovery_pin.bin — DO NOT EDIT.\n\
             pub(crate) const EMBEDDED_PIN: &[u8] = &{bytes:?};\n"
        )
    } else if unpinned_dev {
        // NON-SECURE, TEST-ONLY pin: a 33-byte classical (X25519 32 bytes of the
        // recognizable 0xA5 pattern, then the 0x00 "ML-KEM absent" tag). This
        // MUST NEVER SHIP — it exists only so the lib test suite can build without
        // a real `recovery_pin.bin`. A real build embeds a genuine pin or (below)
        // fails closed.
        let mut test_pin = vec![0xA5u8; 32];
        test_pin.push(0x00);
        format!(
            "// @generated by build.rs — NON-SECURE TEST PIN (unpinned-dev). NEVER SHIP.\n\
             pub(crate) const EMBEDDED_PIN: &[u8] = &{test_pin:?};\n"
        )
    } else {
        panic!(
            "recovery_pin.bin missing — run maxsecu-setup and rebuild, or use \
             --features unpinned-dev for tests"
        );
    };

    std::fs::write(&gen_path, generated).expect("write recovery_pin_gen.rs");
}
