//! Phase-6 smoke test: the DEV portable-server boots from an empty data dir over
//! real loopback TLS, lays out the portable folder + the dev cert/D5, and a client
//! connects over the self-signed cert and runs POST /v1/bootstrap with the one-time
//! secret (201) and a wrong secret (401). Proves "it just runs".

use std::sync::Arc;

use base64::engine::general_purpose::STANDARD as B64;
use base64::Engine;
use http_body_util::Full;
use hyper::body::Bytes;
use hyper::{Request, StatusCode};
use hyper_util::rt::TokioIo;
use tokio::net::TcpStream;
use tokio_rustls::rustls::pki_types::{CertificateDer, ServerName};
use tokio_rustls::rustls::{ClientConfig, RootCertStore};
use tokio_rustls::TlsConnector;

use maxsecu_portable_server::config::{ColdTierCfg, LauncherConfig, Profile};
use maxsecu_portable_server::layout::Layout;
use maxsecu_portable_server::run::prepare;

#[tokio::test]
async fn dev_server_boots_and_client_bootstraps() {
    let tmp = std::env::temp_dir().join(format!(
        "mxps-smoke-{}-{}",
        std::process::id(),
        maxsecu_crypto::random_array::<4>()
            .iter()
            .map(|b| format!("{b:02x}"))
            .collect::<String>()
    ));
    let _ = std::fs::remove_dir_all(&tmp);
    let cfg = LauncherConfig {
        data_dir: tmp.clone(),
        port: 0,
        profile: Profile::Dev,
        database_url: None,
        cold_tier: ColdTierCfg::Off,
        cache_capacity_bytes: 250_000_000_000,
        offload_idle_days: 30,
    };

    // Boot.
    let prepared = prepare(&cfg).await.expect("dev prepare");
    let addr = prepared.local_addr;
    let secret = prepared
        .bootstrap_secret
        .clone()
        .expect("first-run bootstrap secret");
    // Read the server's cert to trust it as the client's pinned root.
    let layout = Layout::ensure(&tmp).unwrap();
    let cert_der = CertificateDer::from(std::fs::read(layout.cert_der_path()).unwrap());

    // GATE: the portable folder was laid out + the dev cert/D5 generated by prepare.
    // (client-pins are exported by `run`, not `prepare` — so assert the
    // prepare-created artifacts here.)
    assert!(layout.tls_dir().is_dir() && layout.blobs_dir().is_dir());
    assert!(layout.cert_der_path().is_file() && layout.d5_pub_path().is_file());

    // Serve in the background.
    tokio::spawn(maxsecu_server::serve(
        prepared.listener,
        prepared.server_config,
        prepared.router,
    ));

    // Build a client that trusts the launcher's self-signed cert.
    let mut roots = RootCertStore::empty();
    roots.add(cert_der).unwrap();
    let provider = Arc::new(tokio_rustls::rustls::crypto::aws_lc_rs::default_provider());
    let client_config = ClientConfig::builder_with_provider(provider)
        .with_safe_default_protocol_versions()
        .unwrap()
        .with_root_certificates(roots)
        .with_no_client_auth();

    let post = |secret: String| {
        let client_config = client_config.clone();
        async move {
            let tcp = TcpStream::connect(addr).await.unwrap();
            let connector = TlsConnector::from(Arc::new(client_config));
            let tls = connector
                .connect(ServerName::try_from("localhost").unwrap(), tcp)
                .await
                .unwrap();
            let (mut sender, conn) = hyper::client::conn::http1::handshake(TokioIo::new(tls))
                .await
                .unwrap();
            tokio::spawn(async move {
                let _ = conn.await;
            });
            let body = serde_json::json!({
                "username": "glassbreak",
                "enc_pub_b64": B64.encode([1u8; 32]),
                "sig_pub_b64": B64.encode([2u8; 32]),
                "bootstrap_secret": secret,
            });
            sender.ready().await.unwrap();
            let req = Request::builder()
                .method("POST")
                .uri("/v1/bootstrap")
                .header("host", "localhost")
                .header("content-type", "application/json")
                .body(Full::new(Bytes::from(body.to_string())))
                .unwrap();
            let resp = sender.send_request(req).await.unwrap();
            resp.status()
        }
    };

    // GATE: wrong secret → 401.
    assert_eq!(
        post("WRONG-secret".to_string()).await,
        StatusCode::UNAUTHORIZED
    );
    // GATE: correct one-time secret → 201 (bootstrap window open, secret matches).
    assert_eq!(post(secret).await, StatusCode::CREATED);

    let _ = std::fs::remove_dir_all(&tmp);
}
