//! Phase-6 / T15 smoke test: the DEV portable-server boots from an empty data dir
//! over real loopback TLS, lays out the portable folder + the dev cert/D5, and
//! serves with **NO bootstrap secret**. Proves the new enrollment reality:
//!   - a client CANNOT enroll (`POST /v1/users`) without a valid registration key
//!     (a bogus key is a `403`, no account created);
//!   - recovery registration (`POST /v1/recovery/register`) is OPEN on a fresh
//!     server (`201`) and CLOSES after the first use (a second attempt is `409`).
//!
//! Proves "it just runs" under the registration-key-only model.

use std::sync::Arc;

use base64::engine::general_purpose::STANDARD as B64;
use base64::Engine;
use http_body_util::Full;
use hyper::body::Bytes;
use hyper::client::conn::http1::SendRequest;
use hyper::{Request, StatusCode};
use hyper_util::rt::TokioIo;
use tokio::net::TcpStream;
use tokio_rustls::rustls::pki_types::{CertificateDer, ServerName};
use tokio_rustls::rustls::{ClientConfig, RootCertStore};
use tokio_rustls::TlsConnector;

use maxsecu_portable_server::config::{ColdTierCfg, LauncherConfig, Profile};
use maxsecu_portable_server::layout::Layout;
use maxsecu_portable_server::run::prepare;

#[tokio::test]
async fn dev_server_boots_and_enforces_registration_key_model() {
    let tmp = std::env::temp_dir().join(format!(
        "mxps-smoke-{}-{}",
        std::process::id(),
        maxsecu_crypto::random_array::<4>()
            .iter()
            .map(|b| format!("{b:02x}"))
            .collect::<String>()
    ));
    let _ = std::fs::remove_dir_all(&tmp);
    let cfg = LauncherConfig {
        data_dir: tmp.clone(),
        port: 0,
        bind: "127.0.0.1".to_owned(),
        public_addr: None,
        profile: Profile::Dev,
        database_url: None,
        cold_tier: ColdTierCfg::Off,
        cache_capacity_bytes: 200_000_000_000,
        offload_idle_days: 30,
        direct_links_enabled: false,
    };

    // Boot. `Prepared` carries NO bootstrap secret — that field is gone (the
    // server no longer generates/prints one); this test compiles only because of
    // that removal.
    let prepared = prepare(&cfg).await.expect("dev prepare");
    let addr = prepared.local_addr;
    // Read the server's cert to trust it as the client's pinned root.
    let layout = Layout::ensure(&tmp).unwrap();
    let cert_der = CertificateDer::from(std::fs::read(layout.cert_der_path()).unwrap());

    // GATE: the portable folder was laid out + the dev cert/D5 generated by prepare.
    assert!(layout.tls_dir().is_dir() && layout.blobs_dir().is_dir());
    assert!(layout.cert_der_path().is_file() && layout.d5_pub_path().is_file());

    // Serve in the background.
    tokio::spawn(maxsecu_server::serve(
        prepared.listener,
        prepared.server_config,
        prepared.router,
    ));

    // Build a client that trusts the launcher's self-signed cert.
    let mut roots = RootCertStore::empty();
    roots.add(cert_der).unwrap();
    let provider = Arc::new(tokio_rustls::rustls::crypto::aws_lc_rs::default_provider());
    let client_config = ClientConfig::builder_with_provider(provider)
        .with_safe_default_protocol_versions()
        .unwrap()
        .with_root_certificates(roots)
        .with_no_client_auth();

    // Open a fresh pinned-TLS HTTP/1.1 connection.
    async fn connect(addr: std::net::SocketAddr, cfg: &ClientConfig) -> SendRequest<Full<Bytes>> {
        let tcp = TcpStream::connect(addr).await.unwrap();
        let connector = TlsConnector::from(Arc::new(cfg.clone()));
        let tls = connector
            .connect(ServerName::try_from("localhost").unwrap(), tcp)
            .await
            .unwrap();
        let (sender, conn) = hyper::client::conn::http1::handshake(TokioIo::new(tls))
            .await
            .unwrap();
        tokio::spawn(async move {
            let _ = conn.await;
        });
        sender
    }

    // POST one JSON body over a fresh connection; return only the status.
    let post = |uri: &'static str, body: serde_json::Value| {
        let client_config = client_config.clone();
        async move {
            let mut sender = connect(addr, &client_config).await;
            sender.ready().await.unwrap();
            let req = Request::builder()
                .method("POST")
                .uri(uri)
                .header("host", "localhost")
                .header("content-type", "application/json")
                .body(Full::new(Bytes::from(body.to_string())))
                .unwrap();
            sender.send_request(req).await.unwrap().status()
        }
    };

    // GATE: enrollment requires a valid registration key. A bogus key is a 403
    // (no account created) — the server closed the old secret-less bootstrap door.
    assert_eq!(
        post(
            "/v1/users",
            serde_json::json!({
                "username": "glassbreak",
                "enc_pub_b64": B64.encode([1u8; 32]),
                "sig_pub_b64": B64.encode([2u8; 32]),
                "registration_key": "definitely-not-a-real-key",
            }),
        )
        .await,
        StatusCode::FORBIDDEN,
        "enrollment without a valid registration key must be 403"
    );

    // GATE: recovery registration is OPEN on a fresh server → 201 the first time.
    let recovery_body = serde_json::json!({
        "enc_pub_b64": B64.encode([3u8; 32]),
        "sig_pub_b64": B64.encode([4u8; 32]),
    });
    assert_eq!(
        post("/v1/recovery/register", recovery_body.clone()).await,
        StatusCode::CREATED,
        "first recovery registration on a fresh server must be 201"
    );
    // GATE: once used, recovery registration is CLOSED (once-only) → 409.
    assert_eq!(
        post("/v1/recovery/register", recovery_body).await,
        StatusCode::CONFLICT,
        "a second recovery registration must be 409 (once-only)"
    );

    let _ = std::fs::remove_dir_all(&tmp);
}
